<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-NIPPIU2" name="TestNGFramework.Assertions" tests="7" failures="1" timestamp="20 Jun 2021 16:15:10 GMT" time="8.816" errors="0">
  <testcase name="e_asset" time="0.058" classname="TestNGFramework.Assertions"/>
  <testcase name="b_assert" time="0.090" classname="TestNGFramework.Assertions"/>
  <testcase name="a_PageLoad" time="8.549" classname="TestNGFramework.Assertions"/>
  <testcase name="f_assert" time="0.020" classname="TestNGFramework.Assertions"/>
  <testcase name="d_assert" time="0.044" classname="TestNGFramework.Assertions"/>
  <testcase name="g_assert" time="0.017" classname="TestNGFramework.Assertions">
    <failure type="java.lang.AssertionError" message="expected [null] but found [Zero - Personal Banking - Loans - Credit Cards]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [Zero - Personal Banking - Loans - Credit Cards]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotSame(Assert.java:509)
	at org.testng.Assert.assertNull(Assert.java:445)
	at org.testng.Assert.assertNull(Assert.java:434)
	at TestNGFramework.Assertions.g_assert(Assertions.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- g_assert -->
  <testcase name="c_assert" time="0.038" classname="TestNGFramework.Assertions"/>
</testsuite> <!-- TestNGFramework.Assertions -->
